### Lesson Numpy


In [8]:
print('Вычисления с помощью Numpy \n\n Задание 1 \n')
import numpy as np

a = np.transpose(np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]))


print("Форма a: {}".format(a.shape))
print('Массив a:\n',a)

a1 = a[:,:1] #Признак 1
a2 = a[:,1:] #Признак 2

print('Признак 1:\n',a1)
print('Признак 2:\n',a2)

mean_a = np.array ([np.mean(a1), np.mean(a2)])

print('Средние значения по каждому признаку (mean_a):\n',mean_a)

print('\n Задание 2 \n')

a_centered = a - mean_a

print('Массив a_centered:\n',a_centered)

print('\n Задание 3 \n')

print('\n разбиваем матрицу a_centered на 2 отдельных столбца \n')

a_centered1 = a_centered[:,:1] 
a_centered2 = a_centered[:,1:] 

print('a_centered1:\n',a_centered1)
print('a_centered2:\n',a_centered2)

print('\n Скалярное произведение столбцов как матриц: \n')
a_centered_sp = a_centered1 @ np.transpose(a_centered2)

print('Массив a_centered_sp:\n',a_centered_sp )

print('\n Делим массив a_centered_sp на  N - 1 где N - число наблюдений\n')

print (np.divide(a_centered_sp, (a.size-1)))


Вычисления с помощью Numpy 

 Задание 1 

Форма a: (5, 2)
Массив a:
 [[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Признак 1:
 [[1]
 [2]
 [3]
 [3]
 [1]]
Признак 2:
 [[ 6]
 [ 8]
 [11]
 [10]
 [ 7]]
Средние значения по каждому признаку (mean_a):
 [2.  8.4]

 Задание 2 

Массив a_centered:
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]

 Задание 3 


 разбиваем матрицу a_centered на 2 отдельных столбца 

a_centered1:
 [[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]
a_centered2:
 [[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]

 Скалярное произведение столбцов как матриц: 

Массив a_centered_sp:
 [[ 2.4  0.4 -2.6 -1.6  1.4]
 [ 0.   0.   0.   0.   0. ]
 [-2.4 -0.4  2.6  1.6 -1.4]
 [-2.4 -0.4  2.6  1.6 -1.4]
 [ 2.4  0.4 -2.6 -1.6  1.4]]

 Делим массив a_centered_sp на  N - 1 где N - число наблюдений

[[ 0.26666667  0.04444444 -0.28888889 -0.17777778  0.15555556]
 [ 0.          0.          0.          0.          0.        ]
 [-0.26666667 -0.04444444  0.28888889  0.17777778 -0.15555556]
 [-0.